import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const SHEET_ID = '1KvL9b3CsKY5RWwxh44BLuoekDwKs8cTHUdSFhpfZr7M';
const GID = '235965803';
const CSV_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${GID}`;

const outputPath = path.resolve('src/data.ts');

function parseCSVLine(line) {
  const values = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      values.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  values.push(current.trim());
  return values;
}

try {
  console.log('Fetching data from Google Sheets...');
  const data = execSync(`curl -L "${CSV_URL}"`, { encoding: 'utf-8' });
  const cleanData = data.replace(/\r/g, '');
  const lines = cleanData.split('\n').filter(line => line.trim());

  if (lines.length === 0) {
    console.log('No data found in CSV.');
    process.exit(1);
  }

  const headers = parseCSVLine(lines[0]).map(h => h.trim());
  console.log('Detected Headers:', headers);
  
  const jsonData = lines.slice(1).map((line) => {
    const values = parseCSVLine(line);
    const obj = {};
    headers.forEach((header, i) => {
      if (header) {
        let val = values[i] || '';
        if (val.startsWith('"') && val.endsWith('"')) {
          val = val.substring(1, val.length - 1);
        }
        obj[header] = val.trim();
      }
    });
    return obj;
  }).filter(obj => obj.Gothra);

  if (jsonData.length === 0) {
    console.log('No records with "Gothra" found. Check if the sheet is public.');
    process.exit(1);
  }

  const content = `// This file is automatically generated from Google Sheets. Do not edit manually.
export interface AbhivadhayeRecord {
  Gothra: string;
  Rishi1: string;
  Rishi2: string;
  Rishi3: string;
  Rishi4?: string;
  Rishi5?: string;
  Rishi6?: string;
  Rishi7?: string;
  Veda: string;
  Suthra: string;
  [key: string]: string | undefined;
}

export const abhivadhayeData: AbhivadhayeRecord[] = ${JSON.stringify(jsonData, null, 2)};\n`;
  fs.writeFileSync(outputPath, content);
  console.log(`Successfully synced ${jsonData.length} Gothra records from Google Sheets!`);
} catch (err) {
  console.error('Error fetching data:', err.message);
  process.exit(1);
}
