export const abhivadhayeData = [
    { Gothra: "Kundina Gowthama", Rishi1: "Angirasa", Rishi2: "Ayasya", Rishi3: "Kundina Gowthama", Veda: "Rig", Suthra: "AaSvakAyana" },
    { Gothra: "Bharadwaja", Rishi1: "Angirasa", Rishi2: "Bhaarhaspatya", Rishi3: "Bharadwaja", Veda: "Rig", Suthra: "SaankhyAyana" },
    { Gothra: "Vadula Savarni &Yaska", Rishi1: "Bhargava", Rishi2: "Vaitahavya", Rishi3: "Saavedasa", Veda: "Rig", Suthra: "Kousheetakee" },
    { Gothra: "Maitreya", Rishi1: "Bhargava", Rishi2: "Daivodasa", Rishi3: "Vadhryasva", Veda: "Yajur", Suthra: "Aapasthambha" },
    { Gothra: "Shaunaka", Rishi1: "Shaunaka(ekarsheya)", Rishi2: "", Rishi3: "", Veda: "Yajur", Suthra: "HiraNyakESi" },
    { Gothra: "Gartsamada", Rishi1: "Bhargava", Rishi2: "Sunahotra", Rishi3: "Gartsamada", Veda: "Yajur", Suthra: "BhAradhwAja" },
    { Gothra: "Vatsa/Srivatsa", Rishi1: "Bhargava", Rishi2: "Chyavana", Rishi3: "Apnavana", Veda: "Yajur", Suthra: "BhOdhAyana" },
    { Gothra: "Vatsa/Srivatsa", Rishi1: "Apnuvat", Rishi2: "Aurava", Rishi3: "Jamadagnya", Veda: "", Suthra: "" },
    { Gothra: "Aarshtisena", Rishi1: "Bhargava", Rishi2: "Chyavana", Rishi3: "Apnavana", Veda: "", Suthra: "" },
    { Gothra: "Bidasa", Rishi1: "Bhargava", Rishi2: "Chyavana", Rishi3: "Apnavana/Apnuvat", Veda: "", Suthra: "" },
    { Gothra: "Shatamarshana", Rishi1: "Angirasa", Rishi2: "Powrukutsa", Rishi3: "Traasatasya", Veda: "Saama", Suthra: "Gobhila" },
    { Gothra: "AAtreya/Krishnatreya", Rishi1: "Atreya", Rishi2: "Aarchanaasa", Rishi3: "Syaavaasva", Veda: "Saama", Suthra: "KhAdhira" },
    { Gothra: "Vadhbhutaka", Rishi1: "Atreya", Rishi2: "Aarchanaasa", Rishi3: "Vadhbhutaka", Veda: "", Suthra: "" },
    { Gothra: "Gavisthiras", Rishi1: "Atreya", Rishi2: "Gavisthira", Rishi3: "Purvatitha", Veda: "Atarva", Suthra: "KouSika" },
    { Gothra: "Koushika", Rishi1: "Vaiswaamitra", Rishi2: "Aghamarshana", Rishi3: "Koushika", Veda: "", Suthra: "" },
    { Gothra: "Kalabodhana", Rishi1: "Viswaamitra", Rishi2: "AAgamarshana", Rishi3: "Kalabodhana / Kalaboudha", Veda: "", Suthra: "" },
    { Gothra: "Bhargava", Rishi1: "Bhargava", Rishi2: "Tvashta", Rishi3: "Vishvaroopa", Veda: "", Suthra: "" },
    { Gothra: "Viswamitra", Rishi1: "Vaiswaamitra", Rishi2: "Devaraata", Rishi3: "", Veda: "", Suthra: "" },
    { Gothra: "Kowndinya", Rishi1: "Vashista", Rishi2: "Maitraavaruna", Rishi3: "Koundinya", Veda: "", Suthra: "" },
    { Gothra: "Kapinjala", Rishi1: "Vashista", Rishi2: "Aindrapramada", Rishi3: "Abharadvasavya", Veda: "", Suthra: "" },
    { Gothra: "Vashista", Rishi1: "Vashista(ekarsheya)", Rishi2: "", Rishi3: "", Veda: "", Suthra: "" },
    { Gothra: "Haritasa 1", Rishi1: "Harita", Rishi2: "Ambarisha", Rishi3: "Yuvanasva", Veda: "", Suthra: "" },
    { Gothra: "Haritasa 2", Rishi1: "Angirasa", Rishi2: "Ambarisha", Rishi3: "Yuvanasva", Veda: "", Suthra: "" },
    { Gothra: "Gautamasa", Rishi1: "Angirasa", Rishi2: "Aayasyasa", Rishi3: "Gautama", Veda: "", Suthra: "" },
    { Gothra: "Mowdgalya 1", Rishi1: "Angirasa", Rishi2: "Bharmyasva", Rishi3: "Mowdgalya", Veda: "", Suthra: "" },
    { Gothra: "Mowdgalya 2", Rishi1: "Tarkshya", Rishi2: "Bharmyasva", Rishi3: "Mowdgalya", Veda: "", Suthra: "" },
    { Gothra: "Mowdgalya 3", Rishi1: "Angirasa", Rishi2: "Dhavya", Rishi3: "Mowdgalya", Veda: "", Suthra: "" },
    { Gothra: "Sandilya 1", Rishi1: "Kasyapa", Rishi2: "Aavatsaara", Rishi3: "Daivala", Veda: "", Suthra: "" },
    { Gothra: "Sandilya 2", Rishi1: "Kasyapa", Rishi2: "Aavatsaara", Rishi3: "Sandilya", Veda: "", Suthra: "" },
    { Gothra: "Sandilya 3", Rishi1: "Kasyapa", Rishi2: "Daivala", Rishi3: "Asitha", Veda: "", Suthra: "" },
    { Gothra: "Naitruvakaasyapa", Rishi1: "Kasyapa", Rishi2: "Aavatsara", Rishi3: "Naitruva", Veda: "", Suthra: "" },
    { Gothra: "Kutsa", Rishi1: "Aangirasa", Rishi2: "Maandhatra", Rishi3: "Koutsa", Veda: "", Suthra: "" },
    { Gothra: "Kapi", Rishi1: "Angirasa", Rishi2: "Aamahaiya", Rishi3: "Orukshaya", Veda: "", Suthra: "" },
    { Gothra: "Kapila", Rishi1: "Angirasa", Rishi2: "Aamahaiya", Rishi3: "Orukshaya", Veda: "", Suthra: "" },
    { Gothra: "Kanva 1", Rishi1: "Angirasa", Rishi2: "Ajameeda", Rishi3: "Kaanva", Veda: "", Suthra: "" },
    { Gothra: "Kanva 2", Rishi1: "Angirasa", Rishi2: "Kowra", Rishi3: "Kaanva", Veda: "", Suthra: "" },
    { Gothra: "Paraasara", Rishi1: "Vashista", Rishi2: "Saaktya", Rishi3: "Paarasarya", Veda: "", Suthra: "" },
    { Gothra: "Upamanyu", Rishi1: "Vashista", Rishi2: "Aindrapramada", Rishi3: "Bhadravasavya", Veda: "", Suthra: "" },
    { Gothra: "Aagastya", Rishi1: "Aagastya", Rishi2: "Tardhachyuta", Rishi3: "Sowmavaha", Veda: "", Suthra: "" },
    { Gothra: "Gargyasa 1", Rishi1: "Angirasa", Rishi2: "Bharhaspatya", Rishi3: "Bharadwaja", Veda: "", Suthra: "" },
    { Gothra: "Gargyasa 2", Rishi1: "Angirasa", Rishi2: "Sainya", Rishi3: "Gaargya", Veda: "", Suthra: "" },
    { Gothra: "Bhadarayana", Rishi1: "Angirasa", Rishi2: "Paarshadaswa", Rishi3: "Raatitara", Veda: "", Suthra: "" },
    { Gothra: "Kashyapa", Rishi1: "Kasyapa", Rishi2: "Aavatsaara", Rishi3: "Daivala", Veda: "", Suthra: "" },
    { Gothra: "Sankriti 1", Rishi1: "Angirasa", Rishi2: "Kowravidha", Rishi3: "Saankritya", Veda: "", Suthra: "" },
    { Gothra: "Sankriti 2", Rishi1: "Sadhya", Rishi2: "Kowravidha", Rishi3: "Saankritya", Veda: "", Suthra: "" },
    { Gothra: "Suryadhwaja", Rishi1: "Lakhi (Mehrishi)", Rishi2: "Soral", Rishi3: "Binju", Veda: "", Suthra: "" },
    { Gothra: "Daivaratasa", Rishi1: "Viswamitra", Rishi2: "Daivaratasa", Rishi3: "Avudhala", Veda: "", Suthra: "" },
    { Gothra: "Chikitasa", Rishi1: "Viswamitra", Rishi2: "Devarata", Rishi3: "Aghamarshana", Veda: "", Suthra: "" }
];
